apiVersion: v1
kind: Service
metadata:
  name: ftgo-postgres
  labels:
    app.kubernetes.io/name: ftgo-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: ftgo-postgres
