-- =============================================================================
-- V1: Order Service Schema
-- Database: ftgo_order_service
-- Service: ftgo-order-service
--
-- Tables:
--   - orders: Core order entity with state machine
--   - order_line_items: Order line items (part of Order aggregate)
--
-- ID Generation: PostgreSQL IDENTITY columns (replaces shared hibernate_sequence)
--
-- Cross-service references (stored as IDs without FK constraints):
--   - orders.consumer_id       -> ftgo-consumer-service (consumers.id)
--   - orders.restaurant_id     -> ftgo-restaurant-service (restaurants.id)
--   - orders.assigned_courier_id -> ftgo-courier-service (courier.id)
--
-- These references are resolved at runtime via REST API calls or event-driven
-- synchronization. No cross-service foreign keys are created.
-- =============================================================================

CREATE TABLE IF NOT EXISTS orders (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_state                 VARCHAR(50)     NOT NULL DEFAULT 'APPROVED',
    consumer_id                 BIGINT          NOT NULL,
    restaurant_id               BIGINT          NOT NULL,
    assigned_courier_id         BIGINT,
    order_minimum               DECIMAL(19, 2),
    payment_token               VARCHAR(255),
    version                     BIGINT          NOT NULL DEFAULT 0,

    -- Delivery address (embedded Address value object)
    delivery_address_street1    VARCHAR(255),
    delivery_address_street2    VARCHAR(255),
    delivery_address_city       VARCHAR(255),
    delivery_address_state      VARCHAR(255),
    delivery_address_zip        VARCHAR(255),

    -- Lifecycle timestamps
    accept_time                 TIMESTAMP,
    preparing_time              TIMESTAMP,
    ready_for_pickup_time       TIMESTAMP,
    picked_up_time              TIMESTAMP,
    delivered_time              TIMESTAMP,
    delivery_time               TIMESTAMP,
    ready_by                    TIMESTAMP,

    -- Ticket state tracking
    previous_ticket_state       INTEGER,

    created_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_line_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT          NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    menu_item_id    VARCHAR(255),
    name            VARCHAR(255),
    price           DECIMAL(19, 2),
    quantity        INTEGER         NOT NULL
);

-- Indexes for common query patterns
CREATE INDEX idx_orders_consumer_id ON orders (consumer_id);
CREATE INDEX idx_orders_restaurant_id ON orders (restaurant_id);
CREATE INDEX idx_orders_assigned_courier_id ON orders (assigned_courier_id);
CREATE INDEX idx_orders_order_state ON orders (order_state);
CREATE INDEX idx_order_line_items_order_id ON order_line_items (order_id);

COMMENT ON TABLE orders IS 'Order entity - owns the order lifecycle state machine';
COMMENT ON COLUMN orders.consumer_id IS 'Reference to consumer in ftgo-consumer-service (no FK constraint)';
COMMENT ON COLUMN orders.restaurant_id IS 'Reference to restaurant in ftgo-restaurant-service (no FK constraint)';
COMMENT ON COLUMN orders.assigned_courier_id IS 'Reference to courier in ftgo-courier-service (no FK constraint)';
COMMENT ON TABLE order_line_items IS 'Order line items - part of Order aggregate';
