apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-restaurant-service-config
  labels:
    app.kubernetes.io/name: ftgo-restaurant-service
    app.kubernetes.io/component: service
data:
  spring-profiles: "kubernetes"
  datasource-url: "jdbc:postgresql://ftgo-postgres:5432/ftgo_restaurant_service"
