apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-restaurant-service-config
  labels:
    app.kubernetes.io/name: ftgo-restaurant-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: ftgo
data:
  spring-profiles: kubernetes
  java-opts: "-Xmx384m -Xms256m"
