-- =============================================================================
-- V1: Consumer Service Schema
-- Database: ftgo_consumer_service
-- Service: ftgo-consumer-service
--
-- Tables:
--   - consumers: Core consumer entity with embedded PersonName
--
-- ID Generation: PostgreSQL IDENTITY columns (replaces shared hibernate_sequence)
--
-- Cross-service references:
--   None - Consumer is a root aggregate with no foreign key dependencies
-- =============================================================================

CREATE TABLE IF NOT EXISTS consumers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for name-based lookups
CREATE INDEX idx_consumers_last_name ON consumers (last_name);

COMMENT ON TABLE consumers IS 'Consumer entity - owns the consumer aggregate';
COMMENT ON COLUMN consumers.id IS 'Service-local consumer ID (IDENTITY-generated)';
COMMENT ON COLUMN consumers.first_name IS 'Consumer first name (embedded PersonName)';
COMMENT ON COLUMN consumers.last_name IS 'Consumer last name (embedded PersonName)';
