apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-consumer-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: consumer-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-order-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: order-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-restaurant-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: restaurant-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-courier-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: courier-service
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              cpu: 250m
              memory: 384Mi
