apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftgo-staging

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: ftgo
    patch: |
      - op: replace
        path: /metadata/name
        value: ftgo-staging
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: HorizontalPodAutoscaler
    patch: |
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5

commonLabels:
  environment: staging
