apiVersion: v1
kind: Service
metadata:
  name: ftgo-courier-service
  labels:
    app.kubernetes.io/name: ftgo-courier-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: ftgo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ftgo-courier-service
