spring:
  application:
    name: ftgo-order-service
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}/ftgo_order_service
    username: ${SPRING_DATASOURCE_USERNAME:mysqluser}
    password: ${SPRING_DATASOURCE_PASSWORD:mysqlpw}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8085}

restaurant:
  service:
    url: ${RESTAURANT_SERVICE_URL:http://localhost:8081}

consumer:
  service:
    url: ${CONSUMER_SERVICE_URL:http://localhost:8082}

delivery:
  service:
    url: ${DELIVERY_SERVICE_URL:http://localhost:8084}
