-- =============================================================================
-- V1: Courier Service Schema
-- Database: ftgo_courier_service
-- Service: ftgo-courier-service
--
-- Tables:
--   - courier: Core courier entity with availability tracking
--   - courier_actions: Pickup/dropoff action plan (embedded Plan)
--
-- ID Generation: PostgreSQL IDENTITY columns (replaces shared hibernate_sequence)
--
-- Cross-service references (stored as IDs without FK constraints):
--   - courier_actions.order_id -> ftgo-order-service (orders.id)
--
-- The order_id reference is resolved via event-driven communication
-- through ftgo-order-service-api events. No cross-service FK is created.
-- =============================================================================

CREATE TABLE IF NOT EXISTS courier (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available   BOOLEAN         NOT NULL DEFAULT FALSE,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),

    -- Embedded Address value object
    street1     VARCHAR(255),
    street2     VARCHAR(255),
    city        VARCHAR(255),
    state       VARCHAR(255),
    zip         VARCHAR(255),

    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS courier_actions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_id  BIGINT          NOT NULL REFERENCES courier (id) ON DELETE CASCADE,
    order_id    BIGINT,
    time        TIMESTAMP,
    type        VARCHAR(255)
);

-- Indexes for common query patterns
CREATE INDEX idx_courier_available ON courier (available);
CREATE INDEX idx_courier_actions_courier_id ON courier_actions (courier_id);
CREATE INDEX idx_courier_actions_order_id ON courier_actions (order_id);

COMMENT ON TABLE courier IS 'Courier entity - owns the courier aggregate with delivery plan';
COMMENT ON COLUMN courier.available IS 'Courier availability for new deliveries';
COMMENT ON TABLE courier_actions IS 'Courier delivery actions - part of embedded Plan';
COMMENT ON COLUMN courier_actions.order_id IS 'Reference to order in ftgo-order-service (no FK constraint)';
