apiVersion: v1
kind: Service
metadata:
  name: ftgo-mysql
  namespace: ftgo
  labels:
    app.kubernetes.io/name: ftgo-mysql
    app.kubernetes.io/component: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: ftgo-mysql
