apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer-service
    bounded-context: consumer
spec:
  type: ClusterIP
  selector:
    app: consumer-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
