apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer-service
    part-of: ftgo
spec:
  type: ClusterIP
  selector:
    app: consumer-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
