apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app: api-gateway
data:
  CONSUMER_SERVICE_URL: "http://consumer-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  RESTAURANT_SERVICE_URL: "http://restaurant-service:8080"
  COURIER_SERVICE_URL: "http://courier-service:8080"
  FTGO_CORS_ALLOWED_ORIGINS: "http://localhost:3000"
  SPRING_PROFILES_ACTIVE: "default"
