apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-service-config
  labels:
    app: restaurant-service
    bounded-context: restaurant
    tier: application
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  JAVA_OPTS: "-Xms256m -Xmx512m"
  SPRING_DATASOURCE_URL: "jdbc:mysql://ftgo-mysql:3306/ftgo?useSSL=false&allowPublicKeyRetrieval=true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,readiness,liveness"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
