apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-api-gateway-config
  labels:
    app.kubernetes.io/name: ftgo-api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: ftgo
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
  FTGO_ORDER_SERVICE_URL: "http://ftgo-order-service:8080"
  FTGO_CONSUMER_SERVICE_URL: "http://ftgo-consumer-service:8080"
  FTGO_RESTAURANT_SERVICE_URL: "http://ftgo-restaurant-service:8080"
  FTGO_COURIER_SERVICE_URL: "http://ftgo-courier-service:8080"
  REDIS_HOST: "ftgo-redis"
  REDIS_PORT: "6379"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus,gateway"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://ftgo-zipkin:9411/api/v2/spans"
