apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-restaurant-service-config
  labels:
    app.kubernetes.io/name: ftgo-restaurant-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: ftgo
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:mysql://ftgo-mysql:3306/ftgo?useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_FLYWAY_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
