apiVersion: v1
kind: ConfigMap
metadata:
  name: ftgo-consumer-service-config
  namespace: ftgo
data:
  SPRING_APPLICATION_NAME: ftgo-consumer-service
  SERVER_PORT: "8081"
  MYSQL_HOST: ftgo-mysql
  MYSQL_PORT: "3306"
  SPRING_DATASOURCE_URL: "jdbc:mysql://ftgo-mysql:3306/ftgo_consumer_service"
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  TRACING_SAMPLING_RATE: "1.0"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
