apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftgo-consumer-service
  labels:
    app.kubernetes.io/name: ftgo-consumer-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: ftgo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ftgo-consumer-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
