-- =============================================================================
-- V1: Restaurant Service Schema
-- Database: ftgo_restaurant_service
-- Service: ftgo-restaurant-service
--
-- Tables:
--   - restaurants: Core restaurant entity
--   - restaurant_menu_items: Menu items (ElementCollection of Restaurant)
--
-- ID Generation: PostgreSQL IDENTITY columns (replaces shared hibernate_sequence)
--
-- Cross-service references:
--   None - Restaurant is a root aggregate with no foreign key dependencies.
--   Other services reference restaurant IDs via REST API calls.
-- =============================================================================

CREATE TABLE IF NOT EXISTS restaurants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)    NOT NULL,

    -- Embedded Address value object
    street1     VARCHAR(255),
    street2     VARCHAR(255),
    city        VARCHAR(255),
    state       VARCHAR(255),
    zip         VARCHAR(255),

    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS restaurant_menu_items (
    restaurant_id   BIGINT          NOT NULL REFERENCES restaurants (id) ON DELETE CASCADE,
    id              VARCHAR(255)    NOT NULL,
    name            VARCHAR(255),
    price           DECIMAL(19, 2),

    PRIMARY KEY (restaurant_id, id)
);

-- Indexes for common query patterns
CREATE INDEX idx_restaurants_name ON restaurants (name);

COMMENT ON TABLE restaurants IS 'Restaurant entity - owns the restaurant aggregate';
COMMENT ON TABLE restaurant_menu_items IS 'Menu items - ElementCollection of Restaurant aggregate';
COMMENT ON COLUMN restaurant_menu_items.restaurant_id IS 'Owning restaurant (intra-service FK)';
